### PR TITLE
0.19 compatible

### PR DESCRIPTION
**Pull request by Hermanverschooten**
I have used the other PR #13 as my inspiration, but upgraded the fixtures to be 0.19 compatible.
All test are passing.

### CODE REVIEW

**Comment by Hermanverschooten** [comment]
as @joecorkerton noted in PR #13, this does not work when using --optimize.

when using the following code:
```elm
module UserProject exposing (Asset(..), cornucopia, main)

type Asset
    = Asset String

cornucopia =
    Asset "elm_logo.svg"

main : Program () Asset msg
main =
    Platform.worker { init = \_ -> ( cornucopia, Cmd.none ), update = \_ m -> ( m, Cmd.none ), subscriptions = always Sub.none }
```

without --optimize this becomes:
```javascript
var elm$something$UserProject$cornucopia = elm$something$UserProject$Asset('elm_logo.svg');
```

with --optimize : 
```javascript
var elm$something$UserProject$Asset = elm$core$Basics$identity;
var elm$core$Basics$identity = function (x) {
    return x;
};
var elm$something$UserProject$cornucopia = 'elm_logo.svg';
```

It seems to me we lose too much information in the optimisation to use this technique.

**Comment by ABinaryGeek** [comment]
What's the viability of doing the work over the elm code rather than the compiled code?

As I see it, it would involve putting this loader before `elm-webpack-loader` and whatever modification to that loader as required to allow it to accept input via the pipeline rather than directly through files - which looks to be the painful point as it probably means writing out to a temporary directory because them elm compiler can't - as far as I know - handle anything else.

**Comment by toastal** [comment]
I'm currently using this PR branch, but having to disable the optimization is a major let-down. It's kind of a surprise that this is independent from the webpack plugin.

**Comment by michaelglass** [comment]
thank you!

**Comment by toastal** [comment]
Does this address the optimization issue? @michaelglass If not, there should be something in the README about it.

**Comment by michaelglass** [comment]
There are a bunch of small bugs around the optimize flag, so we don't use it internally. Also we stopped using webpack internally, so I'd love for this to move to elm-community.

**Comment by michaelglass** [comment]
there are a bunch of small issues with `--optimize` so I think it's best to avoid for now.

**Pull request merged**
