### PR TITLE
add more webpack versions to the matrix

### PR DESCRIPTION
**Pull request by michaelglass**
builds on #11, will merge both #11 and this if tests pass

### CODE REVIEW

**Comment by muelli** [comment]
It seems travis is unhappy with Webpack 2.6.1. Maybe that version can be considered as being too old...

**Comment by muelli** [comment]
Now it seems to be unhappy with Elm 0.17.
Given that 0.19 is coming very soon now, maybe dropping 0.17 is an option.

**Comment by michaelglass** [comment]
just a flake

**Comment by michaelglass** [comment]
@muelli sorry about the (extensive) delay!

**Comment by muelli** [comment]
no problemo.

any chance that we can consume the new version through npm?
https://www.npmjs.com/package/elm-assets-loader currently lists 0.3.0 as latest version.

**Comment by michaelglass** [comment]
@muelli released. thanks for the reminder

**Pull request merged**
